sudo: false
language: rust
matrix:
  include:
  - rust: nightly
  - rust: beta
  - rust: stable
script:
- cargo build

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

after_success:
 - travis-cargo coveralls --no-sudo --verify
